### ISSUE TITLE
Identify subtasks for packaging Deisa w. pip

### ISSUE THREAD

**Issue by jbigot** [pdidev/deisa#5]
`Dask-distributed` fork depends on a specific version of `Dask`. So we should pin the version of `Dask` we use.
* With current version of dependencies, there seems to be an issue with `map_block`.
* There's another issue with task not being able to transition from state to state `Task object is not subscriptable`.

**Comment by benoitmartin88** [comment]
TODO for current Deisa version:
- [ ] pip packaging:
  - [x] dask 2023.11.0 -> https://pypi.org/project/dask/2023.11.0/
  - [ ] distributed fork
  - [ ] deisa -> https://pypi.org/project/deisa/
- [ ] [spack packaging](https://github.com/Maison-de-la-Simulation/spack):
  - [x] dask -> https://github.com/Maison-de-la-Simulation/spack/blob/stable/packages/py-dask/package.py
  - [ ] update py-distributed -> https://github.com/Maison-de-la-Simulation/spack/blob/stable/packages/py-distributed/package.py
  - [ ] update deisa -> https://github.com/Maison-de-la-Simulation/spack/blob/stable/packages/deisa/package.py

**Comment by benoitmartin88** [comment]
Tasks are now split in https://github.com/pdidev/deisa/issues/12 and https://github.com/pdidev/deisa/issues/13
